# Configuracion de la aplicacion Tienda Virtual
app.name=Tienda Virtual
app.version=1.0.0

# Limites de validacion (en COP)
payment.creditcard.max-amount=10000000
payment.paypal.max-amount=8000000
payment.crypto.min-amount=10000

# Habilitar modulos observadores
observer.inventory.enabled=true
observer.facturation.enabled=true
observer.notification.enabled=true
